name: Laravel

on:
  push:
    branches: ["main", "devel"]
  pull_request:
    branches: ["main", "devel"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/checkout@v3
        # CREATE .ENV FILE
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        # INSTALL PHP DEPENDENCIES
      - name: Install Dependencies
        run: composer install
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
        # INSTALL NODE MODULES
      - name: Install dependencies
        run: npm install
        # PRETTIER
      - name: Prettier check
        run: npx prettier --check .
